FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages for pyenv.
RUN apt-get update && \
	apt-get install -y \
		build-essential \
		git \
		wget \
		cmake \
		curl \
		make \
		libssl-dev \
		zlib1g-dev \
		libbz2-dev \
		libreadline-dev \
		libsqlite3-dev \
		llvm \
		libncurses5-dev \
		libncursesw5-dev \
		xz-utils \
		tk-dev \
		libffi-dev \
		liblzma-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN cd /tmp && \
	wget https://github.com/neovim/neovim/releases/download/v0.10.1/nvim-linux64.tar.gz && \
	tar zxf nvim*.tar.gz && \
	cp -R nvim-linux64 /opt && \
	echo 'export PATH=$PATH:/opt/nvim-linux64/bin' >> ~/.bashrc
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
	echo 'export PYENV_ROOT=$HOME/.pyenv'  >> ~/.bashrc && \
	echo 'command -v pyenv > /dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc && \
	echo 'eval "$(pyenv init -)"' >> ~/.bashrc && \
	. ~/.bashrc && \
	pyenv install 3.10.12 && \
	pyenv global 3.10.12
RUN curl -sSL https://install.python-poetry.org | python3 - && \
	echo 'export PATH=$PATH:$HOME/.local/bin' >> ~/.bashrc && \
	. ~/.bashrc && \
	poetry config virtualenvs.in-project true

WORKDIR /workspace
COPY . .

CMD ["/bin/bash"]
